RememberBruce/Controllers/BruceController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RememberBruce.Models;

namespace RememberBruce.Controllers
{
    public class BruceController : Controller
    {
        private BruceContext db;
        public BruceController(BruceContext context)
        {
            db = context;
        }

        [HttpGet("/home")]
        public IActionResult Index()
        {
            return View("Dashboard");
        }

        [HttpGet("about")]
        public IActionResult Summary()
        {
            return View("AboutBruce");
        }

        [HttpGet("truck/new")]
        public IActionResult NewTruck()
        {
            int? loggedInID = HttpContext.Session.GetInt32("userId");
            if (loggedInID == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View("AddTruck");
        }

        [HttpPost("truck/add")]
        //Currently as it is, the database is not receiving the form data once submitted. 
        public IActionResult Create(Truck newTruck)
        {
            int? loggedInID = HttpContext.Session.GetInt32("userId");
            if (loggedInID == null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                newTruck.UserId = (int)loggedInID;
                db.Add(newTruck);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = newTruck.TruckId });
            }
            else
            {
                if (newTruck.Location == null)
                {
                    ModelState.AddModelError("Location", "The Location field is required.");
                }
                return View("AddTruck", newTruck);
            }
        }

        [HttpGet("location")]
        public IActionResult Detail()
        {
            return View("Detail");
        }



        [HttpGet("edit")]
        public IActionResult Edit()
        {
            return View("EditTruck");
        }

    }
}

RememberBruce/Views/Bruce/AboutBruce.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Bruce</title>
    <link rel="stylesheet" href="/css/style.css">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
</head>

<body class="bg">

    <div style="display: flex; justify-content: flex-end">
        <a type="button" role="button" href="/home" class="btn btn-primary ">Home</a>
    </div>


    <h1 class="text-lg-center" style="color: #00C7C3; text-shadow: 2px 2px #040404;">
        Bruce The Caboose</h1>

    <div class="row bg" style="justify-content: center;">
        <video width="720" height="340" controls>
            <source src="/videos/32666FDF-E5E9-4E47-9192-6F5BF904D600.mp4" type="video/mp4">
            @* <source src="" type=""> *@
            Your browser does not support the video tag.
        </video>
    </div>

    <div class="row" style="color: #EFFCFC;">
        <div class="col"
            style="background-color: #5A5A59; box-shadow: 5px 10px 18px; padding: 10px; background: rgb(27, 27, 8, 0.6);">
            <partial name="_BruceSummary" />
        </div>
    </div>

    <div>
        <div>
            <partial name="_BruceImages" />
        </div>
    </div>


    <div class="row" style="display:flex; justify-content: center">
        <a href="https://www.facebook.com/rememberbrucethecaboose/" class='fab fa-facebook-square' id="facebook"></a>
        <a href="https://www.instagram.com/rememberbrucethecaboose/?hl=en" class='fab fa-instagram' id="instagram"></a>
    </div>
</body>

</html>

RememberBruce/Views/Bruce/AddTruck.cshtml
@model Truck

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <style>
        @**{outline:1pxdottedred;}*@.bg {
            /* The image used */
            background-image: url("https://utahhome.me/wp-content/uploads/2014/07/stansbury-park-shutterstock_42888772.jpg");

            /* Full height */
            height: 100%;

            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            background-attachment: fixed;
        }

        #instagram {
            background: radial-gradient(circle at 30% 107%,
                    #fdf497 0%,
                    #fdf497 5%,
                    #fd5949 45%,
                    #d6249f 60%,
                    #285aeb 90%);
            -webkit-background-clip: text;
            /* Also define standard property for compatibility */
            background-clip: text;
            -webkit-text-fill-color: transparent;

            font-size: 40px;
            /*change this to change the size*/
        }

        #facebook {
            font-size: 40px;
        }
    </style>
</head>


<body class="bg">

    <div class="container" style="font-family: Georgia; box-shadow: 5px 10px 18px;">
        <div style="display: flex; justify-content:flex-end;">
            <a href="/home" class="btn btn-success">Home</a>
        </div>

        <div class="row" style="display: flex; justify-content: center;">

            <div class="col" style="text-align: center;">
                <h1>You FOUND One!!!</h1>
                <h4>Tell us where!</h4>
                <form asp-controller="Bruce" asp-action="Create" class="md-form" method="POST">
                    <div class="file-field">
                        <div class="d-flex justify-content-center">
                            <div class="btn btn-mdb-color btn-rounded float-left">
                                <label asp-for="Image"></label>
                                <span asp-validation-for="Image"></span>
                                @using (Html.BeginForm("new", "Content", FormMethod.Post, new
                                {
                                    enctype
                                = "multipart/form-data"
                                }))
                                {
                                    <input asp-for="Image" type="file" name="AddImage" id="AddImage"
                                    onchange="fileCheck(this);">
                                }
                            </div>
                        </div>
                        <div class="d-flex justify-content-center">
                            <div class="form-outline">
                                <label asp-for="Location"></label>
                                <span asp-validation-for="Location"></span>
                                <input asp-for="Location" type="text" id="Location" class="form-control"
                                    aria-describedby="textExample1" placeholder="Location of Truck" />
                                <label class="form-label" for="location" aria-placeholder="Location"></label>
                            </div>
                        </div>
                        <div>
                            <div class="form-floating">
                                <label asp-for="Details"></label>
                                <span asp-validation-for="Details"></span>
                                <textarea asp-for="Details" class="form-control" placeholder="Details" id="Details"
                                    style="height: 100px"></textarea>
                            </div>
                        </div>
                        <div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col" style="text-align: center;">
                <div class="row">
                    <h4>Did your Bruce Truck come with a QR Code?</h4>
                    <p style="font-size: small;">Scan the QR code now if you haven't done so! You can see where this
                        truck has already been to and
                        if
                        this
                        is it's first time, we have you to thank for it!</p>
                    <div>
                        <img src="/img/AandB.jpeg" style="max-width: 50%;" />
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="row" style="display:flex; justify-content: center">
        <a href="https://www.facebook.com/rememberbrucethecaboose/" class='fab fa-facebook-square' id="facebook"></a>
        <a href="https://www.instagram.com/rememberbrucethecaboose/?hl=en" class='fab fa-instagram' id="instagram"></a>
    </div>


</body>


</html>

RememberBruce/Views/Bruce/Dashboard.cshtml
<div class="container mt-3">
    <header class="d-flex justify-content-end">
        <a href="/about">Who is Bruce</a> | search
    </header>
    <div class="text-center">
        <h1>Oh the places you'll go....</h1>
    </div>

    <div class="d-flex justify-contents-around">
        <div style="margin-top: 100px;">
            <img src="/img/placeholder.jpg" alt="pic" width="380px" height="370px">
        </div>
        <div class="text-center ml-5 mr-5">
            <a href="truck/new" class="btn btn-primary align-item-center"
                style="border: 2px solid black; height: 80px; width: 250px; border-radius: 20px;">
                <p>Did you find a Bruce Truck?</p>
                <p>Click Here</p>
            </a>
        </div>
        <div style="margin-top: 100px;" style="width: 650px; height: 350px;">
            <p class="text-center">Bruce's Most Recent Visits</p>
            <table class="table table-striped table-bordered" style="overflow-y: scroll; width: 600px">
                <thead style="background-color: grey;">
                    <tr>
                        <th scope="col">Location</th>
                        <th scope="col">Date Submitted</th>
                        <th scope="col">Name of Submitter</th>
                        <th scope="col">Message</th>
                    </tr>
                </thead>
                <tbody class="overflow-scroll">
                    <tr>
                        <th scope="row">1</th>
                        <td>Mark</td>
                        <td>Otto</td>
                        <td>mdo</td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                        <td>fat</td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td>Larry</td>
                        <td>the Bird</td>
                        <td>twitter</td>
                    </tr>
                    <tr>
                        <th scope="row">1</th>
                        <td>Mark</td>
                        <td>Otto</td>
                        <td>mdo</td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>Jacob</td>
                        <td>Thornton</td>
                        <td>fat</td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td>Larry</td>
                        <td>the Bird</td>
                        <td>twitter</td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>

RememberBruce/Views/Bruce/EditTruck.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <style>
        @**{outline:1pxdottedred;}*@.bg {
            /* The image used */
            background-image: url("https://k1ux2moa2s-flywheel.netdna-ssl.com/wp-content/uploads/2018/06/stansbury-park-utah.jpg");

            /* Full height */
            height: 100%;

            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            background-attachment: fixed;
        }

        #instagram {
            background: radial-gradient(circle at 30% 107%,
                    #fdf497 0%,
                    #fdf497 5%,
                    #fd5949 45%,
                    #d6249f 60%,
                    #285aeb 90%);
            -webkit-background-clip: text;
            /* Also define standard property for compatibility */
            background-clip: text;
            -webkit-text-fill-color: transparent;

            font-size: 40px;
            /*change this to change the size*/
        }

        #facebook {
            font-size: 40px;
        }
    </style>
</head>


<body class="bg">

    <div class="container" style="font-family: Georgia; box-shadow: 5px 10px 18px;">
        <div style="display: flex; justify-content:flex-end;">
            <a href="/home" class="btn btn-success">Home</a>
        </div>

        <div class="row" style="display: flex; justify-content: center;">

            <div class="col" style="text-align: center;">
                <h3>Please make your corrections and resubmit!</h3>

                <form class="md-form">
                    <div class="file-field">
                        <div class="d-flex justify-content-center">
                            <div class="btn btn-mdb-color btn-rounded float-left">
                                <span>Upload photo here!</span>
                                <input type="file">
                            </div>
                        </div>
                        <div class="d-flex justify-content-center">
                            <div class="form-outline">
                                <input type="text" id="location" class="form-control" aria-describedby="textExample1"
                                    placeholder="Location of Truck" />
                                <label class="form-label" for="location" aria-placeholder="Location"></label>
                            </div>
                        </div>
                        <div>
                            <div class="form-floating">
                                <textarea class="form-control" placeholder="Details" id="Details"
                                    style="height: 100px"></textarea>
                                <label for="Details"></label>
                            </div>
                        </div>
                        <div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>

            <div class="col" style="text-align: center;">
                <div class="row">
                    <h4>Did you forget to scan the QR code?</h4>
                    <p style="font-size: small;">No problem! Go ahead and scan the QR code now.</p>
                    <div>
                        <img src="https://gray-kwch-prod.cdn.arcpublishing.com/resizer/bOZkZ_Un8QEIwHZGCGnPPP4_quA=/980x0/smart/cloudfront-us-east-1.images.arcpublishing.com/gray/5A4FDMHJQVDCDDCUUUMVFQEZT4.png"
                            style="max-width: 25%;" />
                    </div>
                </div>
                <div class="row" style="display:flex; justify-content: center; color: #EEF7F6;">
                    <h6>Have Questions?</h6>
                </div>
                <div class="row" style="display:flex; justify-content: center; color: #EEF7F6;">
                    <h4>Reach out to us!</h4>
                </div>
                <div class="row" style="display:flex; justify-content: center">
                    <a href="https://www.facebook.com/rememberbrucethecaboose/" class='fab fa-facebook-square'
                        id="facebook"></a>
                    <a href="https://www.instagram.com/rememberbrucethecaboose/?hl=en" class='fab fa-instagram'
                        id="instagram"></a>
                </div>
            </div>
        </div>

    </div>


</body>


</html>

RememberBruce/Views/Bruce/_BruceImages.cshtml
<div class="slideshow-container">

    <div class="mySlides fade">
        <div class="numbertext">1 / 9</div>
        <img src="/img/AandB.jpeg" style="width:75%">
        <div class="text">Bruce with Big Sister</div>
    </div>

    <div class="mySlides fade">
        <div class="numbertext">2 / 9</div>
        <img src="/img/Brothers1.jpeg" style="width:75%">
        <div class="text">Blackwell Boys</div>
    </div>

    <div class="mySlides fade">
        <div class="numbertext">3 / 9</div>
        <img src="/img/Brothers2.jpeg" style="width:75%">
        <div class="text">Brothers Forever</div>
    </div>

    <div class="mySlides fade">
        <div class="numbertext">4 / 9</div>
        <img src="/img/Cornfield.jpeg" style="width:75%">
        <div class="text">Halloween</div>
    </div>

    <div class="mySlides fade">
        <div class="numbertext">5 / 9</div>
        <img src="/img/DadandB.jpeg" style="width:75%">
        <div class="text">Daddies Litte Mushy</div>
    </div>

    <div class="mySlides fade">
        <div class="numbertext">6 / 9</div>
        <img src="/img/DadandB2.jpeg" style="width:75%">
        <div class="text">Halloween Pumpkins</div>
    </div>

    <div class="mySlides fade">
        <div class="numbertext">7 / 9</div>
        <img src="/img/MomandB.jpeg" style="width:75%">
        <div class="text">Mommies Forever Baby</div>
    </div>

    <div class="mySlides fade">
        <div class="numbertext">8 / 9</div>
        <img src="/img/MomandB2.jpeg" style="width:75%">
        <div class="text">Best Cuddler Ever</div>
    </div>

    <div class="mySlides fade">
        <div class="numbertext">9 / 9</div>
        <img src="/img/Tootsie.jpeg" style="width:75%">
        <div class="text">The Candy Monster</div>
    </div>

    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>

</div>
<br>

<div style="text-align:center">
    <span class="dot" onclick="currentSlide(1)"></span>
    <span class="dot" onclick="currentSlide(2)"></span>
    <span class="dot" onclick="currentSlide(3)"></span>
    <span class="dot" onclick="currentSlide(4)"></span>
    <span class="dot" onclick="currentSlide(5)"></span>
    <span class="dot" onclick="currentSlide(6)"></span>
    <span class="dot" onclick="currentSlide(7)"></span>
    <span class="dot" onclick="currentSlide(8)"></span>
    <span class="dot" onclick="currentSlide(9)"></span>
</div>

@* /**************************************javascript**************************/ *@

<script>
    var slideIndex = 1;
    showSlides(slideIndex);

    function plusSlides(n) {
        showSlides(slideIndex += n);
    }

    function currentSlide(n) {
        showSlides(slideIndex = n);
    }

    function showSlides(n) {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("dot");
        if (n > slides.length) { slideIndex = 1 }
        if (n < 1) { slideIndex = slides.length }
        for (i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";                     }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex - 1].style.display = "block";
        dots[slideIndex - 1].className += " active";
    }
</script>

RememberBruce/Views/Bruce/_BruceSummary.cshtml
<p class="text-md-center text-justify">
    Bruce epitomized personality, whether he was stubbornly looking in his parents’ eyes saying “No,” or laughing
    hysterically in an instant. Bruce’s keen eye for sweets, earned him the title of “Candy Monster.” His unique ability
    to locate candy long after his parent’s thought all the candy had been disposed of resulted in the family finding
    him sitting on top of the counter with a sucker in his mouth, on the bench with a tootsie roll, or strolling down
    the hall with chocolate.
    <br>
    <br>
    Bruce filled his two-year tenure on earth with love and family. He loved helping his siblings with chores,
    particularly vacuuming. He loved anything that would roll, including his toy trucks and construction vehicles. With
    the invigorating energy that only a two-year old can muster he got dirty, ran, jumped, climbed, and rode. Yet, with
    the sweet gentleness and trust reserved for one so young, untainted by toil and strife, he cared for his “baby.”
    Then, with cup of “mak” in hand he would crawl into the expecting arms of his mommy and daddy for early morning
    snuggles, whispering “I love you,” in his best monster whisper.
    <br>
    <br>
    His laugh, his smile, his big brown eyes and fierce love will be missed by all as we struggle to adopt his motto
    “Live and love big with all your might.” He will always be our baby boy, our Bruce, our Caboose.
</p>